apiVersion: apps/v1
kind: Deployment
metadata:
  name: quik-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quik-website
  template:
    metadata:
      labels:
        app: quik-website
    spec:
      containers:
        - name: quik-website-container
          image: "ghcr.io/lmartinking/quik-website:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: quik-website-service
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: quik-website
---
# This middleware is used to strip "/quik" from the HTTP request path,
# as the container itself does not know what its route prefix is.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /quik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quik-website-ingress
  annotations:
    ingress.kubernetes.io/class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: quik-website-middleware@kubernetescrd  # {namespace}-{name}@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: irrationalidiom.com
      http:
        paths:
          - path: /quik
            pathType: Prefix
            backend:
              service:
                name: quik-website-service
                port:
                  number: 80
